version: "3.9"
services:
  devops_app:
    image: "hyagohamon/crud-pacientes-final"
    depends_on:
      - prometheus
    ports:
      - "8080:8080"
    networks:
      - dev

  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
    networks:
      - dev

  prometheus:
    image: prom/prometheus
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    #        volumes:
    #            - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - dev



networks:
  dev:
    driver: bridge